# Generated by Django 5.2.10 on 2026-02-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Page view"),
                            ("SEARCH", "Search"),
                            ("ITEM_VIEW", "Item view"),
                            ("MESSAGE", "Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("page_path", models.CharField(blank=True, max_length=255)),
                ("search_query", models.CharField(blank=True, max_length=255)),
                ("session_key", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_events",
                        to="listings.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["activity_type", "created_at"], name="core_userac_activit_847c5b_idx"),
                    models.Index(fields=["user", "created_at"], name="core_userac_user_id_78efad_idx"),
                ],
            },
        ),
    ]
