# Generated by Django 5.2.12 on 2026-03-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='core_userac_activit_470d16_idx',
            old_name='core_userac_activit_847c5b_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='core_userac_user_id_b9a062_idx',
            old_name='core_userac_user_id_78efad_idx',
        ),
    ]
