# Generated by Django 5.2.12 on 2026-03-19 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_userac_activit_847c5b_idx_core_userac_activit_470d16_idx_and_more'),
        ('listings', '0002_rename_listings_it_item_ty_f14ec5_idx_listings_it_item_ty_337ff3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('PAGE_VIEW', 'Page view'), ('SEARCH', 'Search'), ('ITEM_VIEW', 'Item view'), ('ITEM_REPORT', 'Item report'), ('CLAIM_SUBMISSION', 'Claim submission'), ('CLAIM_REVIEW', 'Claim review'), ('MESSAGE', 'Message')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CLAIM_SUBMITTED', 'Claim submitted'), ('CLAIM_APPROVED', 'Claim approved'), ('CLAIM_REJECTED', 'Claim rejected')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link_path', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='listings.claim')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='listings.item')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='core_notifi_recipie_4e71b2_idx'), models.Index(fields=['notification_type', 'created_at'], name='core_notifi_notific_d4d13f_idx')],
            },
        ),
    ]
