# Generated by Django 5.2.12 on 2026-03-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_useractivity_activity_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CLAIM_SUBMITTED', 'Claim submitted'), ('CLAIM_APPROVED', 'Claim approved'), ('CLAIM_REJECTED', 'Claim rejected'), ('ITEM_RETURNED', 'Item returned')], max_length=32),
        ),
    ]
