# Generated by Django 5.2.10 on 2026-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("USER", "User"), ("ADMIN", "Admin")],
                default="USER",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
