# Generated by Django 5.2.12 on 2026-03-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='item',
            new_name='listings_it_item_ty_337ff3_idx',
            old_name='listings_it_item_ty_f14ec5_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='listings_it_created_935d5a_idx',
            old_name='listings_it_created_23d88b_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='listings_it_event_d_9b1444_idx',
            old_name='listings_it_event_d_4c0d71_idx',
        ),
    ]
