# Generated by Django 5.2.12 on 2026-03-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3154fc_idx',
            old_name='chat_messag_convers_01a95d_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_is_read_872c73_idx',
            old_name='chat_messag_is_read_611ea6_idx',
        ),
    ]
